version: "3.7"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'koritsu-www:latest'
    container_name: koritsu-web
    hostname: koritsu.test
    volumes:
      - koritsu-data:/data/github/koritsu-www/storage
    networks:
      default:
        aliases:
          - api.koritsu.test
    environment:
      - POSTGRES_DATABASE=apiato
      - POSTGRES_USER=homestead
      - POSTGRESL_PASSWORD=secret
      - POSTGRES_HOST=db
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
        - db
        - pgadmin

  db:
    image: postgres
    restart: always
    container_name: koritsu-db
    environment:
      POSTGRES_DB: apiato
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.5
    restart: always
    container_name: koritsu-db-pgadmin
    hostname: db.koritsu.test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@koritsu.test
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8181:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:
  koritsu-data: