source 'http://rubygems.org'

# library gems
# only uncomment these if need newer version that included in OpenStudio Installer
#gem 'openstudio-extension', github: 'NREL/OpenStudio-extension-gem', branch: 'develop'
#gem 'openstudio-standards', github: 'NREL/openstudio-standards', branch: 'develop'

# measure gems
# todo - I should prboably change these to specific release instead of develop before I make a branch for it
gem 'openstudio-model-articulation', '0.4.0'
# gem 'openstudio-common-measures', github: 'NREL/openstudio-common-measures-gem', branch: 'develop'
gem 'openstudio-common-measures', '0.4.0'
# gem 'openstudio-ee', github: 'NREL/openstudio-ee-gem', branch: 'develop'
gem 'openstudio-ee', '0.4.0'
gem 'openstudio-aedg', '0.4.0'
# todo - the urban geometry measure is failing, maybe need different branch or gem relese to use with OpenStudio 3.0.1
#gem 'urbanopt-geojson', github: 'URBANopt/urbanopt-geojson-gem', branch: 'develop'
# gem 'openstudio-analysis', '1.2.0'

# other gems
gem 'parallel', '~> 1.19', '>= 1.19.2'
gem 'rubyzip', '2.3.0'
# gem 'open3','0.1.0'
gem 'minitest'